# Generated by Django 6.0.8 on 2026-10-04 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aadhaar_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=12, null=True, unique=True
                    ),
                ),
                ("aadhaar_verified", models.BooleanField(default=False)),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("mobile", models.CharField(db_index=True, max_length=20)),
                ("alternate_mobile", models.CharField(blank=True, max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(0, "Not Available"), (1, "Male"), (2, "Female")],
                        db_index=True,
                        default=0,
                        null=True,
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="persons/photos/"
                    ),
                ),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "person",
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="PersonAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Home"),
                            (2, "Permanent"),
                            (3, "Correspondence"),
                            (4, "Office"),
                            (5, "Hostel"),
                            (99, "Other"),
                        ],
                        db_index=True,
                        default=1,
                    ),
                ),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("landmark", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "person_address",
                "ordering": ["person", "address_type"],
            },
        ),
        migrations.CreateModel(
            name="PersonContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Mobile"),
                            (2, "Email"),
                            (3, "WhatsApp"),
                            (4, "Alternate Mobile"),
                            (5, "Landline"),
                            (6, "Emergency Contact"),
                            (99, "Other"),
                        ],
                        db_index=True,
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "person_contact",
                "ordering": ["person", "contact_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contact_type", "value"), name="uq_contact_type_value"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PersonIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identity_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Aadhaar"),
                            (2, "PAN"),
                            (3, "Passport"),
                            (4, "Driving License"),
                            (5, "Voter ID"),
                            (6, "Birth Certificate"),
                            (99, "Other"),
                        ],
                        db_index=True,
                    ),
                ),
                ("identity_number", models.CharField(db_index=True, max_length=100)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identities",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "person_identity",
                "ordering": ["person", "identity_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("identity_type", "identity_number"),
                        name="uq_identity_type_number",
                    )
                ],
            },
        ),
    ]
