# Generated by Django 6.0.8 on 2026-10-04 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employment",
            name="department",
        ),
        migrations.RemoveField(
            model_name="employment",
            name="designation",
        ),
        migrations.RemoveField(
            model_name="employment",
            name="person",
        ),
        migrations.RemoveField(
            model_name="employment",
            name="school",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Designation",
        ),
        migrations.DeleteModel(
            name="Employment",
        ),
    ]
