# Generated by Django 6.0.8 on 2026-10-04 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_remove_employment_department_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identity_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Aadhaar"),
                            (2, "PAN"),
                            (3, "Passport"),
                            (4, "Driving License"),
                            (5, "Voter ID"),
                            (6, "Birth Certificate"),
                            (99, "Other"),
                        ],
                        db_index=True,
                    ),
                ),
                ("identity_number", models.CharField(db_index=True, max_length=100)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identities",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "person_identity",
                "ordering": ["person", "identity_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("identity_type", "identity_number"),
                        name="uq_identity_type_number",
                    )
                ],
            },
        ),
    ]
