# Generated by Django 6.0.8 on 2026-10-04 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_personidentity"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Mobile"),
                            (2, "Email"),
                            (3, "WhatsApp"),
                            (4, "Alternate Mobile"),
                            (5, "Landline"),
                            (6, "Emergency Contact"),
                            (99, "Other"),
                        ],
                        db_index=True,
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "person_contact",
                "ordering": ["person", "contact_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contact_type", "value"), name="uq_contact_type_value"
                    )
                ],
            },
        ),
    ]
