# Generated by Django 6.0.8 on 2026-10-04 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_personcontact"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Home"),
                            (2, "Permanent"),
                            (3, "Correspondence"),
                            (4, "Office"),
                            (5, "Hostel"),
                            (99, "Other"),
                        ],
                        db_index=True,
                        default=1,
                    ),
                ),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("landmark", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "person_address",
                "ordering": ["person", "address_type"],
            },
        ),
    ]
