# Generated by Django 6.0.8 on 2026-10-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admission_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Not Available"), (1, "Male"), (2, "Female")],
                        db_index=True,
                        default=0,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "aadhaar_number",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="students/photos/"
                    ),
                ),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("admission_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "student",
                "ordering": ["admission_number"],
            },
        ),
    ]
