# Generated by Django 6.0.8 on 2026-10-04 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admission_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Not Available"), (1, "Male"), (2, "Female")],
                        db_index=True,
                        default=0,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "aadhaar_number",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="students/photos/"
                    ),
                ),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("admission_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "student",
                "ordering": ["admission_number"],
            },
        ),
        migrations.CreateModel(
            name="StudentParent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Father"),
                            (2, "Mother"),
                            (3, "Guardian"),
                            (4, "Grandparent"),
                            (99, "Other"),
                        ],
                        db_index=True,
                    ),
                ),
                ("is_primary_contact", models.BooleanField(default=False)),
                ("can_pickup_student", models.BooleanField(default=True)),
                ("receives_sms", models.BooleanField(default=True)),
                ("receives_whatsapp", models.BooleanField(default=True)),
                ("receives_email", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_relationships",
                        to="people.person",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_parent",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "person", "relationship_type"),
                        name="unique_student_parent",
                    )
                ],
            },
        ),
    ]
