# Generated by Django 6.0.8 on 2026-10-04 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_person_aadhaar_number_person_aadhaar_verified"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentParent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("FATHER", "Father"),
                            ("MOTHER", "Mother"),
                            ("GUARDIAN", "Guardian"),
                            ("GRANDPARENT", "Grandparent"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_primary_contact", models.BooleanField(default=False)),
                ("can_pickup_student", models.BooleanField(default=True)),
                ("receives_sms", models.BooleanField(default=True)),
                ("receives_whatsapp", models.BooleanField(default=True)),
                ("receives_email", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_relationships",
                        to="hr.person",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_parent",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "person", "relationship_type"),
                        name="unique_student_parent",
                    )
                ],
            },
        ),
    ]
