# Generated by Django 6.0.8 on 2026-10-04 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentParent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Father"),
                            (2, "Mother"),
                            (3, "Guardian"),
                            (4, "Grandparent"),
                            (99, "Other"),
                        ],
                        db_index=True,
                    ),
                ),
                ("is_primary_contact", models.BooleanField(default=False)),
                ("can_pickup_student", models.BooleanField(default=True)),
                ("receives_sms", models.BooleanField(default=True)),
                ("receives_whatsapp", models.BooleanField(default=True)),
                ("receives_email", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_relationships",
                        to="people.person",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_parent",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "person", "relationship_type"),
                        name="unique_student_parent",
                    )
                ],
            },
        ),
    ]
