# Generated by Django 6.0.8 on 2026-10-04 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_studentparent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="gender",
        ),
    ]
