# Generated by Django 6.0.8 on 2026-10-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_remove_student_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Not Available"), (1, "Male"), (2, "Female")],
                db_index=True,
                default=0,
            ),
        ),
    ]
