# Generated by Django 6.0.8 on 2026-10-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemoRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("institution_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("mobile", models.CharField(max_length=20)),
                (
                    "institution_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "School"),
                            (2, "College"),
                            (3, "University"),
                            (4, "Coaching Institute"),
                            (5, "Training Center"),
                        ]
                    ),
                ),
                (
                    "student_strength",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "New"),
                            (2, "Contacted"),
                            (3, "Qualified"),
                            (4, "Demo Scheduled"),
                            (5, "Converted"),
                            (6, "Rejected"),
                        ],
                        default=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "demo_request",
                "ordering": ["-created_at"],
            },
        ),
    ]
