# Generated by Django 6.0.8 on 2026-10-04 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_employment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resignation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason_type",
                    models.CharField(
                        choices=[
                            ("RESIGNED", "Resigned"),
                            ("RETIRED", "Retired"),
                            ("TERMINATED", "Terminated"),
                            ("CONTRACT_ENDED", "Contract Ended"),
                            ("TRANSFERRED", "Transferred"),
                            ("DECEASED", "Deceased"),
                            ("ABSCONDED", "Absconded"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("resignation_date", models.DateField(help_text="Last working day")),
                (
                    "reason_details",
                    models.TextField(blank=True, help_text="Detailed explanation"),
                ),
                (
                    "relieving_letter",
                    models.FileField(
                        blank=True, null=True, upload_to="hr/resignations/"
                    ),
                ),
                ("exit_interview_notes", models.TextField(blank=True)),
                ("is_rehire_eligible", models.BooleanField(default=True)),
                (
                    "employment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resignation",
                        to="hr.employment",
                    ),
                ),
            ],
            options={
                "db_table": "resignation",
                "ordering": ["-resignation_date"],
            },
        ),
    ]
