# Generated by Django 6.0.8 on 2026-10-04 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_resignation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Resignation",
        ),
    ]
