# Generated by Django 6.0.8 on 2026-10-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0005_resignation"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="aadhaar_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=12, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="aadhaar_verified",
            field=models.BooleanField(default=False),
        ),
    ]
