# Generated by Django 6.0.8 on 2026-10-04 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_person_aadhaar_number_person_aadhaar_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="employee_code",
        ),
    ]
