# Generated by Django 6.0.8 on 2026-10-04 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("hr", "0006_resignation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary subject of the teacher"
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "employment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="hr.employment",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teachers",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "teacher_subject",
                "ordering": ["employment", "subject"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employment", "subject"), name="uq_teacher_subject"
                    )
                ],
            },
        ),
    ]
