# Generated by Django 6.0.8 on 2026-10-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0007_teachersubject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="school",
        ),
    ]
