# Generated by Django 6.0.8 on 2026-10-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0007_remove_person_employee_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Not Available"), (1, "Male"), (2, "Female")],
                db_index=True,
                default=0,
            ),
        ),
    ]
