# Generated by Django 6.0.8 on 2026-10-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_remove_department_school"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="department",
            name="uq_department_school_code",
        ),
        migrations.RemoveConstraint(
            model_name="department",
            name="uq_department_school_name",
        ),
    ]
