# Generated by Django 6.0.8 on 2026-10-04 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0009_alter_person_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="gender",
        ),
    ]
