# Generated by Django 6.0.8 on 2026-10-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0010_remove_person_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="gender",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "Not Available"), (1, "Male"), (2, "Female")],
                db_index=True,
                default=0,
                null=True,
            ),
        ),
    ]
