# Generated by Django 6.0.8 on 2026-10-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0011_remove_department_uq_department_school_code_and_more"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("school", "code"), name="uq_department_school_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="uq_department_school_name"
            ),
        ),
    ]
