# Generated by Django 6.0.8 on 2026-10-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0012_department_uq_department_school_code_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="department",
            name="uq_department_school_code",
        ),
        migrations.RemoveConstraint(
            model_name="department",
            name="uq_department_school_name",
        ),
        migrations.RemoveField(
            model_name="department",
            name="school",
        ),
    ]
