# Generated by Django 6.0.8 on 2026-10-04 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0013_remove_department_uq_department_school_code_and_more"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="school",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="organizations.school",
            ),
            preserve_default=False,
        ),
    ]
