# Generated by Django 6.0.8 on 2026-10-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0016_remove_department_uq_department_school_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="school",
        ),
    ]
