# Generated by Django 6.0.8 on 2026-10-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0017_remove_department_school"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="teachersubject",
            name="uq_teacher_subject",
        ),
        migrations.DeleteModel(
            name="TeacherSubject",
        ),
    ]
