# Generated by Django 6.0.8 on 2026-10-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0018_remove_teachersubject_uq_teacher_subject_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Resignation",
        ),
    ]
