# Generated by Django 6.0.8 on 2026-10-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0019_delete_resignation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employment",
        ),
    ]
