# Generated by Django 6.0.8 on 2026-10-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0020_delete_employment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Department",
        ),
    ]
