# Generated by Django 6.0.8 on 2026-10-03 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0003_studentdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LEAVE", "Leave"),
                            ("HALF_DAY", "Half Day"),
                        ],
                        max_length=20,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "attendance_date")},
            },
        ),
    ]
