# Generated by Django 6.0.8 on 2026-10-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique institution code (e.g., SCH001, DPSDELHI, IITD)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official name of the institution", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary official email address",
                        max_length=254,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Main contact number", max_length=20
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Complete postal address"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="City where institution is located",
                        max_length=100,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, help_text="State or province", max_length=100
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="India", help_text="Country name", max_length=100
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether institution is currently active in the system",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
                "db_table": "school",
                "ordering": ["name"],
            },
        ),
    ]
