# Generated by Django 6.0.8 on 2026-10-04 02:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique board code",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Board name",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Board",
                "verbose_name_plural": "Boards",
                "db_table": "board",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique school code",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Official school name", max_length=255
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="Short name used in reports",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique URL-friendly identifier",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="School registration number",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "affiliation_number",
                    models.CharField(
                        blank=True,
                        help_text="Board affiliation number",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "udise_code",
                    models.CharField(
                        blank=True,
                        help_text="UDISE code",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "gst_number",
                    models.CharField(
                        blank=True,
                        help_text="GST registration number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Official school website"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Official school email", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Primary contact number", max_length=20
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True, help_text="Primary address", max_length=255
                    ),
                ),
                ("city", models.CharField(blank=True, db_index=True, max_length=100)),
                ("state", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "country",
                    models.CharField(db_index=True, default="India", max_length=100),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="GPS latitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="GPS longitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="schools/logos/"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, null=True, upload_to="schools/favicons/"
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        blank=True,
                        help_text="Primary branding color (HEX)",
                        max_length=20,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        blank=True,
                        help_text="Secondary branding color (HEX)",
                        max_length=20,
                    ),
                ),
                (
                    "academic_session_start_month",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="Month when academic session starts (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
                "db_table": "school",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolBoardRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(blank=True, max_length=100)),
                ("affiliation_number", models.CharField(blank=True, max_length=100)),
                ("registration_date", models.DateField()),
                ("remarks", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="school_registrations",
                        to="organizations.board",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_registrations",
                        to="organizations.school",
                    ),
                ),
            ],
            options={
                "db_table": "school_board_registration",
            },
        ),
        migrations.CreateModel(
            name="SchoolBoardWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "withdrawal_date",
                    models.DateField(help_text="Date of withdrawal/cancellation"),
                ),
                ("reason", models.TextField(help_text="Reason for withdrawal")),
                (
                    "reason_type",
                    models.CharField(
                        choices=[
                            ("VOLUNTARY", "Voluntary Withdrawal"),
                            ("BOARD_CHANGE", "Changed Board"),
                            ("NON_COMPLIANCE", "Non Compliance"),
                            ("MERGER", "School Merger"),
                            ("CLOSURE", "School Closed"),
                            ("OTHER", "Other"),
                        ],
                        default=None,
                        max_length=30,
                    ),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True,
                        help_text="Official withdrawal/cancellation document",
                        null=True,
                        upload_to="school_board_withdrawals/",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration",
                    models.OneToOneField(
                        help_text="Board registration being withdrawn",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal",
                        to="organizations.schoolboardregistration",
                    ),
                ),
            ],
            options={
                "verbose_name": "School Board Withdrawal",
                "verbose_name_plural": "School Board Withdrawals",
                "db_table": "school_board_withdrawal",
                "ordering": ["-withdrawal_date"],
            },
        ),
        migrations.AddIndex(
            model_name="schoolboardregistration",
            index=models.Index(
                fields=["school", "board"], name="school_boar_school__a6c022_idx"
            ),
        ),
    ]
