# Generated by Django 6.0.8 on 2026-10-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="schools/logos/"),
        ),
        migrations.AddField(
            model_name="school",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
