# Generated by Django 6.0.8 on 2026-10-04 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique school code",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Official school name", max_length=255
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="Short name used in reports",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique URL-friendly identifier",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="School registration number",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "affiliation_number",
                    models.CharField(
                        blank=True,
                        help_text="Board affiliation number",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "udise_code",
                    models.CharField(
                        blank=True,
                        help_text="UDISE code",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "gst_number",
                    models.CharField(
                        blank=True,
                        help_text="GST registration number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Official school website"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Official school email", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Primary contact number", max_length=20
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True, help_text="Primary address", max_length=255
                    ),
                ),
                ("city", models.CharField(blank=True, db_index=True, max_length=100)),
                ("state", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "country",
                    models.CharField(db_index=True, default="India", max_length=100),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="GPS latitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="GPS longitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="schools/logos/"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, null=True, upload_to="schools/favicons/"
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        blank=True,
                        help_text="Primary branding color (HEX)",
                        max_length=20,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        blank=True,
                        help_text="Secondary branding color (HEX)",
                        max_length=20,
                    ),
                ),
                (
                    "academic_session_start_month",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="Month when academic session starts (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
                "db_table": "school",
                "ordering": ["name"],
            },
        ),
    ]
