# Generated by Django 6.0.8 on 2026-10-04 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_school"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolBoardRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(blank=True, max_length=100)),
                ("affiliation_number", models.CharField(blank=True, max_length=100)),
                ("registration_date", models.DateField()),
                ("remarks", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="school_registrations",
                        to="organizations.board",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_registrations",
                        to="organizations.school",
                    ),
                ),
            ],
            options={
                "db_table": "school_board_registration",
                "indexes": [
                    models.Index(
                        fields=["school", "board"],
                        name="school_boar_school__a6c022_idx",
                    )
                ],
            },
        ),
    ]
