# Generated by Django 6.0.8 on 2026-10-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_schoolboardregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
