# Generated by Django 6.0.8 on 2026-10-04 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_board_website"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolBoardWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "withdrawal_date",
                    models.DateField(help_text="Date of withdrawal/cancellation"),
                ),
                ("reason", models.TextField(help_text="Reason for withdrawal")),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True,
                        help_text="Official withdrawal/cancellation document",
                        null=True,
                        upload_to="school_board_withdrawals/",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration",
                    models.OneToOneField(
                        help_text="Board registration being withdrawn",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal",
                        to="organizations.schoolboardregistration",
                    ),
                ),
            ],
            options={
                "verbose_name": "School Board Withdrawal",
                "verbose_name_plural": "School Board Withdrawals",
                "db_table": "school_board_withdrawal",
                "ordering": ["-withdrawal_date"],
            },
        ),
    ]
