# Generated by Django 6.0.8 on 2026-10-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_schoolboardwithdrawal"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolboardwithdrawal",
            name="reason_type",
            field=models.CharField(
                choices=[
                    ("VOLUNTARY", "Voluntary Withdrawal"),
                    ("BOARD_CHANGE", "Changed Board"),
                    ("NON_COMPLIANCE", "Non Compliance"),
                    ("MERGER", "School Merger"),
                    ("CLOSURE", "School Closed"),
                    ("OTHER", "Other"),
                ],
                default=None,
                max_length=30,
            ),
        ),
    ]
